@startuml ResetPasswordActivity

|**Client**|
start
:Login form;
:Send form;

if (Valid input ?) then (Yes)
    :Redirect to dashboard;
    stop
else (No)
    :Click on "Forgot password";
    :Enter recovery email;

    |**Backend**|
    :Send reset link via email;

    |**Client**|
    :Click on reset link;
    :Enter new password;
    :Confirm password;

    if (Valid input ?) then (No)
        |**Client**|
        :Display error message;
        :Allow user to retry;
        stop
    else (yes)
        |**Backend**|
        :Update password;
        :Redirect to login;
        stop
    endif
endif

@enduml
