@startuml RegisterLoginActivity


|**Client**|
start
repeat :LoginPage;
if (Have an account) then (Yes)
    :Login form;
    :Send form;
else (No)
    :Signup form;
    :Send form;
endif
|**Backend**|
:Validation;
backward :Redirection page;
repeat while (Valid input ?) is (No) not (Yes)
stop
@enduml