@startuml DoubleOptIn

actor  User
participant "Frontend" as Frontend
participant "Backend" as Backend
participant "Database" as Database

User -> Frontend : Enter Email in newsletter form
Frontend -> Backend : Sent Post request /subscribe
Backend -> Email : Request available data
Email -> User : Send confirmation link

User -> Frontend : Clicks confirmation link
Frontend -> Backend : GET request to /confirm-subscription
Backend -> Finalize subscription 
Backend -> Frontend : Display success message

@enduml