@startuml ResettingPassword

actor  User
participant "Frontend" as Frontend
participant "Backend" as Backend
participant "Database" as Database
participant "Email Service" as Email


User -> Frontend : Access "Forgot password"
Frontend -> User : Displays reset form
User -> Frontend : Enter email
Frontend -> Backend : Sends POST request (/reset-password)
Backend -> Database : check if email already exist
Database -> Backend : Test result

alt Email found
    Backend -> Email : Send reset link with token
    Email -> User : Reset email with link
    Backend -> Frontend : Display confirmation
    Frontend -> User : Display advice to check his inbox
else Email not found
    Backend -> Frontend : Display error message
    Frontend -> User : Message - "No account found with this email"
end

User -> Frontend : Use reset link with timed token
Frontend -> Backend : send request GET /reset-password with bound token
Backend -> Database : check if token is valid
Database -> Backend : Test result

alt Token is valid
    Backend -> Frontend : Display new password form
    User -> Frontend : Send new password
    Frontend -> Backend : POST request with reset-password form value
    Backend -> Database : Update hashed password
    Database -> Backend : send confirmation
    Backend -> Frontend : Display password updated message
    Frontend -> User : Message  - "Password successfully updated"

else Invalid token or expired
    Backend -> Frontend : Display error message
    Frontend -> User: Message - "Invalid or expired link"
end

@enduml